name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      preset:
        description: 'Preset (release/clang-tidy)'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - clang-tidy
      os:
        description: 'OS for build'
        required: false
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - windows-latest

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            preset: release
            qt_arch: linux_gcc_64
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            preset: release
            qt_arch: linux_gcc_64
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            preset: release
            qt_arch: win64_msvc2022_64

    steps:
      - uses: actions/checkout@v4

      - name: Test arch (Linux)
        if: runner.os == 'Linux'
        run: uname -a

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          target: 'desktop'
          arch: ${{ matrix.qt_arch }}

      - name: Install Clang (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Configure
        run: >
          cmake
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test arch (Linux)
        if: runner.os == 'Linux'
        run: uname -a

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          target: 'desktop'
          arch: linux_gcc_64

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy clang

      - name: Configure (clang-tidy)
        run: cmake --preset clang-tidy

      - name: Build (clang-tidy)
        run: cmake --build build/clang-tidy
